version: "3.8"
volumes:
  satisfactory-data:
services:
  satisfactory:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7777:7777/udp
      - 15000:15000/udp
      - 15777:15777/udp
    volumes:
      - satisfactory-data:/home/steam/.config:rw